services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webhook_fastapi
    ports:
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./log:/app/log:rw
    networks:
      - dokploy-network
    restart: unless-stopped
    command: >
      gunicorn main:app
      -k uvicorn.workers.UvicornWorker
      -w 2
      -b 0.0.0.0:9001
      --timeout 120

networks:
  dokploy-network:
    external: true